# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["Pol Piella Abadia"]
description = ""
language = "swift"
manifest_version = 2
name = "Campaign Sent Webhook"
service_id = ""

[local_server]

  [local_server.backends]

  [local_server.dictionaries]

    [local_server.dictionaries.secrets]
      file = "local.json"
      format = "json"
