name: Push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:latest

    steps:
      - uses: actions/checkout@v3

      - run: swift --version

      - name: Swift Build
        run: swift build -c release -Xswiftc -Osize --triple wasm32-unknown-wasi

      - name: Optimize Wasm Binary
        run: wasm-opt -O2 -o ./.build/release/CampaignSent.wasm ./.build/release/CampaignSent.wasm

      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@main

      - name: Package for Compute@Edge
        run: fastly compute pack --wasm-binary ./.build/release/CampaignSent.wasm

      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions/deploy@main
        with:
          service_id: ${{ secrets.FASTLY_SERVICE_ID }}
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
